# addresses from https://datacrystal.romhacking.net/wiki/Pok%C3%A9mon_Red/Blue:RAM_map
# https://github.com/pret/pokered/blob/91dc3c9f9c8fd529bb6e8307b58b96efa0bec67e/constants/event_constants.asm


### Battle ###

### Player ###
PLAYER_NAME_ADDR_RANGE = range(0xD158, 0xD163)
PLAYER_PARTY_COUNT_ADDR = 0xD163

### Party ###
PARTY_OT_NAME_SIZE = 10
PARTY_NICKNAME_SIZE = 10

PLAYER_PARTY_ADDR = 0xD163

PARTY_COUNT_OFFSET = 0x0

### Box ###
BOX_ADDR = 0xDA80

### Pokemon ###
POKEMON_STRUCTURE_SIZE = 44

POKEMON_ID_OFFSET = 0x0
POKEMON_CURRENT_HP_OFFSET_RANGE = range(0x1, 0x3)
#POKEMON_FALSE_LEVEL_OFFSET = 0x3
POKEMON_STATUS_OFFSET = 0x4

POKEMON_TYPE1_OFFSET = 0x5
POKEMON_TYPE2_OFFSET = 0x6

POKEMON_CATCH_RATE_OFFSET = 0x7

POKEMON_MOVE1_OFFSET = 0x8
POKEMON_MOVE2_OFFSET = 0x9
POKEMON_MOVE3_OFFSET = 0xA
POKEMON_MOVE4_OFFSET = 0xB

POKEMON_TRAINER_ID_OFFSET_RANGE = range(0xC, 0xE)
POKEMON_EXP_OFFSET_RANGE = range(0xE, 0x11)

POKEMON_HP_EV_OFFSET_RANGE = range(0x11, 0x13)
POKEMON_ATTACK_EV_OFFSET_RANGE = range(0x13, 0x15)
POKEMON_DEFENSE_EV_OFFSET_RANGE = range(0x15, 0x17)
POKEMON_SPEED_EV_OFFSET_RANGE = range(0x17, 0x19)
POKEMON_SPECIAL_EV_OFFSET_RANGE = range(0x19, 0x1B)

POKEMON_ATTACK_DEFENSE_IV_OFFSET = 0x1B
POKEMON_SPEED_SPECIAL_IV_OFFSET = 0x1C

POKEMON_PP_MOVE1_OFFSET = 0x1D
POKEMON_PP_MOVE2_OFFSET = 0x1E
POKEMON_PP_MOVE3_OFFSET = 0x1F
POKEMON_PP_MOVE4_OFFSET = 0x20

POKEMON_LEVEL_OFFSET = 0x21

POKEMON_MAX_HP_OFFSET_RANGE = range(0x22, 0x24)
POKEMON_ATTACK_OFFSET_RANGE = range(0x24, 0x26)
POKEMON_DEFENSE_OFFSET_RANGE = range(0x26, 0x28)
POKEMON_SPEED_OFFSET_RANGE = range(0x28, 0x2A)
POKEMON_SPECIAL_OFFSET_RANGE = range(0x2A, 0x2C)


### Pokedex ###
POKEDEX_OWN_ADDR_RANGE = range(0xD2F7, 0xD30A)
POKEDEX_SEEN_ADDR_RANGE = range(0xD30A, 0xD31D)

### Inventory ###
INVENTORY_ADDR = 0xD31D
STORAGE_ADDR = 0xD53A
MONEY_ADDR_RANGE = range(0xD347, 0xD34A)

